ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER USRETL01 IDENTIFIED BY Corso2024; 

COMMIT;

----------------------------------------------------
-- Abilitazioni per creare STORED PROCEDURE
----------------------------------------------------
GRANT CREATE PROCEDURE TO USRETL01;

COMMIT;

----------------------------------------------------
-- Abilitazioni USRETL01
----------------------------------------------------
GRANT CONNECT TO USRETL01;
GRANT SELECT ON DBETL.SOCIETA TO USRETL01;
GRANT SELECT ON DBETL.FATTURE TO USRETL01;
GRANT SELECT ON DBETL.ANAGRAFE_DIPENDENTI TO USRETL01;
GRANT SELECT ON DBETL.STIPENDI_DIPEN TO USRETL01;
GRANT SELECT ON DBETL.COMUNI TO USRETL01;
GRANT SELECT ON DBETL.UFFICI TO USRETL01;
GRANT SELECT ON DBETL.TASK_DIPENDENTI TO USRETL01;
GRANT SELECT ON DBETL.DIPENDENTI TO USRETL01;
GRANT SELECT ON DBETL.PROGETTI TO USRETL01;
GRANT SELECT ON DBETL.TB_02_UTENTI TO USRETL01;
GRANT SELECT ON DBETL.TB_IMPIEGATI TO USRETL01;
GRANT SELECT ON DBETL.TB_ORDINI TO USRETL01;
GRANT SELECT ON DBETL.TB_02_LIBRI TO USRETL01;
GRANT SELECT ON DBETL.TB_02_PRESTITO_LIBRO TO USRETL01;
GRANT SELECT ON DBETL.ATTORI TO USRETL01;
GRANT SELECT ON DBETL.RECITA TO USRETL01;
GRANT SELECT ON DBETL.FILM TO USRETL01;
GRANT SELECT ON DBETL.PROIEZIONI TO USRETL01;
GRANT SELECT ON DBETL.SALE TO USRETL01;
GRANT SELECT ON DBETL.AEROPORTI TO USRETL01;
GRANT SELECT ON DBETL.VOLI TO USRETL01;
GRANT SELECT ON DBETL.AEREO TO USRETL01;
GRANT SELECT ON DBETL.DIPE_AZIENDA TO USRETL01;
GRANT SELECT ON DBETL.UFFICIO TO USRETL01;
GRANT SELECT ON DBETL.BONUS TO USRETL01;
GRANT SELECT ON DBETL.MARKET_CLIENTI TO USRETL01;
GRANT SELECT ON DBETL.MARKET_FATTURE TO USRETL01;
GRANT SELECT ON DBETL.MARKET_PRODOTTI TO USRETL01;
GRANT SELECT ON DBETL.MARKET_FORNITORI TO USRETL01;
GRANT SELECT ON DBETL.HOTEL TO USRETL01;
GRANT SELECT ON DBETL.HOTEL_CLIENTI TO USRETL01;
GRANT SELECT ON DBETL.HOTEL_PREN TO USRETL01;
GRANT SELECT ON DBETL.ANAG_CLI TO USRETL01;
GRANT SELECT ON DBETL.VENDITE TO USRETL01;

CREATE OR REPLACE SYNONYM "USRETL01"."SOCIETA" FOR "DBETL"."SOCIETA";
CREATE OR REPLACE SYNONYM "USRETL01"."FATTURE" FOR "DBETL"."FATTURE";
CREATE OR REPLACE SYNONYM "USRETL01"."ANAGRAFE_DIPENDENTI" FOR "DBETL"."ANAGRAFE_DIPENDENTI";
CREATE OR REPLACE SYNONYM "USRETL01"."STIPENDI_DIPEN" FOR "DBETL"."STIPENDI_DIPEN";
CREATE OR REPLACE SYNONYM "USRETL01"."COMUNI" FOR "DBETL"."COMUNI";
CREATE OR REPLACE SYNONYM "USRETL01"."UFFICI" FOR "DBETL"."UFFICI";
CREATE OR REPLACE SYNONYM "USRETL01"."TASK_DIPENDENTI" FOR "DBETL"."TASK_DIPENDENTI";
CREATE OR REPLACE SYNONYM "USRETL01"."DIPENDENTI" FOR "DBETL"."DIPENDENTI";
CREATE OR REPLACE SYNONYM "USRETL01"."PROGETTI" FOR "DBETL"."PROGETTI";
CREATE OR REPLACE SYNONYM "USRETL01"."TB_02_UTENTI" FOR "DBETL"."TB_02_UTENTI";
CREATE OR REPLACE SYNONYM "USRETL01"."TB_IMPIEGATI" FOR "DBETL"."TB_IMPIEGATI";
CREATE OR REPLACE SYNONYM "USRETL01"."TB_ORDINI" FOR "DBETL"."TB_ORDINI";
CREATE OR REPLACE SYNONYM "USRETL01"."TB_02_LIBRI" FOR "DBETL"."TB_02_LIBRI";
CREATE OR REPLACE SYNONYM "USRETL01"."TB_02_PRESTITO_LIBRO" FOR "DBETL"."TB_02_PRESTITO_LIBRO";
CREATE OR REPLACE SYNONYM "USRETL01"."ATTORI" FOR "DBETL"."ATTORI";
CREATE OR REPLACE SYNONYM "USRETL01"."RECITA" FOR "DBETL"."RECITA";
CREATE OR REPLACE SYNONYM "USRETL01"."FILM" FOR "DBETL"."FILM";
CREATE OR REPLACE SYNONYM "USRETL01"."PROIEZIONI" FOR "DBETL"."PROIEZIONI";
CREATE OR REPLACE SYNONYM "USRETL01"."SALE" FOR "DBETL"."SALE";
CREATE OR REPLACE SYNONYM "USRETL01"."AEROPORTI" FOR "DBETL"."AEROPORTI";
CREATE OR REPLACE SYNONYM "USRETL01"."VOLI" FOR "DBETL"."VOLI";
CREATE OR REPLACE SYNONYM "USRETL01"."AEREO" FOR "DBETL"."AEREO";
CREATE OR REPLACE SYNONYM "USRETL01"."DIPE_AZIENDA" FOR "DBETL"."DIPE_AZIENDA";
CREATE OR REPLACE SYNONYM "USRETL01"."UFFICIO" FOR "DBETL"."UFFICIO";
CREATE OR REPLACE SYNONYM "USRETL01"."BONUS" FOR "DBETL"."BONUS";
CREATE OR REPLACE SYNONYM "USRETL01"."MARKET_CLIENTI" FOR "DBETL"."MARKET_CLIENTI";
CREATE OR REPLACE SYNONYM "USRETL01"."MARKET_FATTURE" FOR "DBETL"."MARKET_FATTURE";
CREATE OR REPLACE SYNONYM "USRETL01"."MARKET_PRODOTTI" FOR "DBETL"."MARKET_PRODOTTI";
CREATE OR REPLACE SYNONYM "USRETL01"."MARKET_FORNITORI" FOR "DBETL"."MARKET_FORNITORI";
CREATE OR REPLACE SYNONYM "USRETL01"."HOTEL" FOR "DBETL"."HOTEL";
CREATE OR REPLACE SYNONYM "USRETL01"."HOTEL_CLIENTI" FOR "DBETL"."HOTEL_CLIENTI";
CREATE OR REPLACE SYNONYM "USRETL01"."HOTEL_PREN" FOR "DBETL"."HOTEL_PREN";
CREATE OR REPLACE SYNONYM "USRETL01"."ANAG_CLI" FOR "DBETL"."ANAG_CLI";
CREATE OR REPLACE SYNONYM "USRETL01"."VENDITE" FOR "DBETL"."VENDITE";

COMMIT;

